// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );




class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oyZJf1eKQs9LVzzIczYq0gS7_b5XRWA',
    appId: '1:638170804330:web:20e1d13071286abfce1a13',
    messagingSenderId: '638170804330',
    projectId: 'fir-demo-a8a96',
    authDomain: 'fir-demo-a8a96.firebaseapp.com',
    storageBucket: 'fir-demo-a8a96.firebasestorage.app',
    measurementId: 'G-WGKZ896W5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSN4h0AsqJVmD4OlwzURfpxCUKZPR1o9E',
    appId: '1:638170804330:android:195f6887bdbf939bce1a13',
    messagingSenderId: '638170804330',
    projectId: 'fir-demo-a8a96',
    storageBucket: 'fir-demo-a8a96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwD5t39bQ2L9h1ZeCEK-CmYYwqThT3tTQ',
    appId: '1:638170804330:ios:f091b1bb47bc250ece1a13',
    messagingSenderId: '638170804330',
    projectId: 'fir-demo-a8a96',
    storageBucket: 'fir-demo-a8a96.firebasestorage.app',
    iosBundleId: 'com.example.microflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwD5t39bQ2L9h1ZeCEK-CmYYwqThT3tTQ',
    appId: '1:638170804330:ios:f091b1bb47bc250ece1a13',
    messagingSenderId: '638170804330',
    projectId: 'fir-demo-a8a96',
    storageBucket: 'fir-demo-a8a96.firebasestorage.app',
    iosBundleId: 'com.example.microflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7oyZJf1eKQs9LVzzIczYq0gS7_b5XRWA',
    appId: '1:638170804330:web:dbb877fd25b00b30ce1a13',
    messagingSenderId: '638170804330',
    projectId: 'fir-demo-a8a96',
    authDomain: 'fir-demo-a8a96.firebaseapp.com',
    storageBucket: 'fir-demo-a8a96.firebasestorage.app',
    measurementId: 'G-HN3D2B9EEN',
  );
}
